---
openapi: 3.0.1
info:
  title: API Mobile2You Challenge
  version: v1
paths:
  "/list_titles":
    get:
      summary: List Netflix titles
      tags:
      - Netflix Titles
      parameters:
      - name: filter[release_year][eq]
        in: query
        required: false
        example: 2020
        schema:
          type: integer
      - name: filter[country][eq]
        in: query
        required: false
        example: United States
        schema:
          type: string
      - name: filter[media_type][eq]
        in: query
        required: false
        example: Movie
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              example: [
                {
                  "id": "s148",
                  "title": "A Babysitter's Guide to Monster Hunting",
                  "genre": "Movie",
                  "year": 2020,
                  "country": "United States",
                  "published_at": "2020-10-15T00:00:00.000Z",
                  "description": "Recruited by a secret society of babysitters, a high schooler battles the Boogeyman and his monsters when they nab the boy she's watching on Halloween."
                },
                {
                  "id": "s169",
                  "title": "A Fall from Grace",
                  "genre": "Movie",
                  "year": 2020,
                  "country": "United States",
                  "published_at": "2020-01-17T00:00:00.000Z",
                  "description": "When gentle, law-abiding Grace confesses to killing her new husband, her skeptical young lawyer sets out to uncover the truth. A film by Tyler Perry."
                },
                {
                  "id": "s210",
                  "title": "A New York Christmas Wedding",
                  "genre": "Movie",
                  "year": 2020,
                  "country": "United States",
                  "published_at": "2020-11-05T00:00:00.000Z",
                  "description": "As her wedding nears, a bride-to-be is visited by an angel who reveals what could have been if she'd followed feelings for her childhood best friend."
                },
                {
                  "id": "s7025",
                  "title": "The Wrong Missy",
                  "genre": "Movie",
                  "year": 2020,
                  "country": "United States",
                  "published_at": "2020-05-13T00:00:00.000Z",
                  "description": "Tim thinks he's invited the woman of his dreams on a work retreat to Hawaii, realizing too late he mistakenly texted someone from a nightmare blind date."
                },
                {
                  "id": "s148",
                  "title": "A Babysitter's Guide to Monster Hunting",
                  "genre": "Movie",
                  "year": 2020,
                  "country": "United States",
                  "published_at": "2020-10-15T00:00:00.000Z",
                  "description": "Recruited by a secret society of babysitters, a high schooler battles the Boogeyman and his monsters when they nab the boy she's watching on Halloween."
                },
                {
                  "id": "s169",
                  "title": "A Fall from Grace",
                  "genre": "Movie",
                  "year": 2020,
                  "country": "United States",
                  "published_at": "2020-01-17T00:00:00.000Z",
                  "description": "When gentle, law-abiding Grace confesses to killing her new husband, her skeptical young lawyer sets out to uncover the truth. A film by Tyler Perry."
                },
                {
                  "id": "s210",
                  "title": "A New York Christmas Wedding",
                  "genre": "Movie",
                  "year": 2020,
                  "country": "United States",
                  "published_at": "2020-11-05T00:00:00.000Z",
                  "description": "As her wedding nears, a bride-to-be is visited by an angel who reveals what could have been if she'd followed feelings for her childhood best friend."
                },
                {
                  "id": "s7025",
                  "title": "The Wrong Missy",
                  "genre": "Movie",
                  "year": 2020,
                  "country": "United States",
                  "published_at": "2020-05-13T00:00:00.000Z",
                  "description": "Tim thinks he's invited the woman of his dreams on a work retreat to Hawaii, realizing too late he mistakenly texted someone from a nightmare blind date."
                }
              ]
    post:
      summary: Insert data from CSV file
      tags:
      - Netflix Titles
      parameters: []
      responses:
        '201':
          description: Titles Saved in database
        '422':
          description: Error
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                file:
                  type: object
                  properties:
                    path:
                      type: string
                      example: "/path_to_file/netflix_titles.csv"
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
